- label: "area:docs"
  files:
    - "**/*.md"

- label: "area:ci"
  files:
    - ".github/workflows/**"
    - ".github/*.yml"
    - ".github/*.yaml"

- label: "area:infra"
  files:
    - "infra/**"
    - "terraform/**"

- label: "area:frontend"
  files:
    - "src/**"

- label: "area:deps"
  files:
    - "package.json"
    - "bun.lock"

- label: "area:docker"
  files:
    - "docker/**"
    - "docker-compose.yml"
    - ".dockerignore"

- label: "area:devcontainer"
  files:
    - ".devcontainer/**"

- label: "area:prisma"
  files:
    - "prisma/**"

