name: Bug report
description: Report a bug to help us improve
labels: [bug]
title: "fix: <short summary>"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the problem?
      placeholder: Expected vs actual behavior
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide numbered steps
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity (optional)
      options:
        - blocker
        - critical
        - major
        - minor
        - trivial
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS/runtime/browser etc.
      value: |
        - OS:
        - Bun:
        - Node (if applicable):
        - Docker:
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      render: shell

