name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "feat: <short summary>"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to achieve?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define done as bullet points
      value: |
        - 
        - 
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
    validations:
      required: false

