name: Auto Label PR
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  label:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout PR HEAD
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          dot: true
